var dataStructure: any = [
  {
    branch: "presentation", // branch reference
    isDisplayed: true, // is the branch displayed
    title: "Presentation", // Title to display
    components: [
      // Form elements
      {
        name: "nom", // attribute name of the input
        question: "Nom *", // Question title
        description: "Quel est votre nom ?", // Question description
        inputType: "textField", // input type
        isBranch: false, // is the value linked to a name branch
        value: "", // value
      },
      {
        name: "prenom",
        question: "Prenom *",
        description: "Quel est votre prenom",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "intitule",
        question: "Intitulé de votre poste *",
        description: "Quel est l'intitulé de votre poste ?",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "role",
        question: "Rôle *",
        description: "Quel est votre rôle dans le projet ?",
        inputType: "select",
        select: [
          "Inventeur",
          "Directeur Generale",
          "Salarie CTO",
          "Chef de projet",
          "Conseiller technique",
        ],
        value: "Directeur Generale",
        isBranch: false,
      },
      {
        name: "entreprise",
        question: "Votre entreprise *",
        description: "Votre entreprise existe t-elle déja ?",
        inputType: "radio",
        radio: ["oui", "non"],
        value: "",
        isBranch: true,
        branchRef: ["isEntreprise", "isNotEntreprise"],
        branchRefValue: "",
      },
    ],
  },
  {
    branch: "isEntreprise",
    isDisplayed: false,
    title: "Votre entreprise",
    components: [
      {
        name: "nomEntreprise",
        question: "Nom de votre entreprise *",
        description: "Quel est le nom de votre entreprise ?",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "webSite",
        question: "Site web *",
        description: "Quel est le site web de votre entreprise ?",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "numeroEnregistrement",
        question: "Numéro d'enregistrement *",
        description:
          "Quel est le numéro d'enregistrement (SIREN, ...) de votre entreprise ?",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "creationDate",
        question: "Année de création *",
        description: "Quel est l'année de création de votre entreprise ?",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "employesNombre",
        question: "Nombre d'employés *",
        description: "Quel est le nombre d'employés de votre entreprise ?",
        inputType: "select",
        select: [
          "Moins de 10",
          "Moins de 30",
          "Moins de 50",
          "Moins de 100",
          "Moins de 200",
          "Moins de 500",
          "Moins de 1000",
          "Plus de 1000",
        ],
        selectRef: [
          "Moins de 10",
          "Moins de 30",
          "Moins de 50",
          "Moins de 100",
          "Moins de 200",
          "Moins de 500",
          "Moins de 1000",
          "Plus de 1000",
        ],
        isBranch: false,
        value: "Moins de 10",
      },
    ],
  },
  {
    branch: "projet",
    isDisplayed: true,
    title: "Projet",
    components: [
      {
        name: "projetNom",
        question: "Nom du projet *",
        description: "Quel est le nom du projet",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "projetDescription",
        question: "Votre projet *",
        description: "Décrivez votre projet *",
        inputType: "textArea",
        isBranch: false,
        value: "",
      },
      {
        name: "projetDoc",
        question: "Document",
        description:
          "Avez-vous un fichier contenant une description complète ?",
        inputType: "radio",
        radio: ["yes", "no"],
        isBranch: false,
        value: "",
      },
      {
        name: "nda",
        question: "Accord NDA",
        description: "Avez vous besoin d'un accord de confidentialité (NDA) ?",
        inputType: "radio",
        radio: ["oui", "non"],
        value: "",
        isBranch: false,
      },
      {
        name: "services",
        question: "Services Altyor *",
        description: "Quels services proposés par Altyor vous intéressent ?",
        inputType: "multiChoice",
        multiChoice: [
          "Réflexion stratégique",
          "Rédaction de cahier des charges",
          "Etude de faisabilité/architecture",
          "Design/conception produit",
          "Etude mécanique",
          "Etude électronique",
          "Prototypage",
          "Industrialisation + Production",
          "Certification",
        ],
        value: [false, false, false, false, false, false, false, false, false],
        isBranch: true,
        branchRef: [
          "reflexionStrategique",
          "redactionDeCahierDesCharges",
          "detail",
          "detail",
          "detail",
          "detail",
          "detail",
          "detail",
          "detail",
        ],
        branchRefValue: [],
      },
    ],
  },
  {
    branch: "detail",
    isDisplayed: false,
    title: "Quelques détails",
    components: [
      {
        name: "connectivite",
        question: "Connectivité",
        description: "Quel sont vos besoins connectique",
        inputType: "multiChoice",
        multiChoice: [
          "Aucun",
          "Dash 7",
          "LTE-M",
          "RFID/NFC",
          "Thread",
          "Zigbee",
          "Bluetooth",
          "GSM/4G/5G",
          "Matter",
          "Satellite",
          "Wifi",
          "Autre",
          "Enocean",
          "Lora",
          "NB-IoT",
          "SigFox",
          "Z-Wave",
        ],
        value: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        isBranch: false,
      },
      {
        name: "capteur",
        question: "Capteurs",
        description: "Quel sont vos besoins captatif",
        inputType: "multiChoice",
        multiChoice: [
          "Aucun",
          "Débit",
          "Humidité",
          "Magnétomètre",
          "Pression",
          "Autre",
          "Accéléromètre",
          "Gaz",
          "I/O",
          "Optique",
          "Proximité",
          "Captatif",
          "Gyroscope",
          "Luminosité",
          "Ouverture/Fermeture",
          "Température",
        ],
        value: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
        isBranch: false,
      },
      {
        name: "energie",
        question: "Energie",
        description: "Quel sont vos besoins énergétique",
        inputType: "multiChoice",
        multiChoice: [
          "Batterie rechargeable",
          "Pile",
          "Prise secteur",
          "Solaire/Lumière",
          "Récupération d'énergie (harvesting)",
          "Autre",
        ],
        value: [false, false, false, false, false, false],
        isBranch: false,
      },
      {
        name: "resistanceEau",
        question: "Résistance a l'eau IP *",
        description: "Quel sont vos besoins d'étanchéité ?",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "prototype",
        question: "Prototype",
        description:
          "Avez-vous déjà un prototype fonctionnel ou une preuve de concept ?",
        inputType: "radio",
        radio: ["oui", "non"],
        value: "",
        isBranch: false,
      },
      {
        name: "fabrication12",
        question: "Nombre de produits à fabriquer",
        description: "Nombre de produits à fabriquer dans les 12 prochain mois",
        inputType: "select",
        select: [
          "Moins de 10",
          "Moins de 100",
          "Moins de 500",
          "Moins de 1000",
          "Moins de 5000",
          "Moins de 10000",
          "Moins de 50000",
          "Moins de 100000",
          "Plus de 100000",
        ],
        value: "",
        isBranch: false,
      },
      {
        name: "fabrication24",
        question: "Nombre de produits à fabriquer",
        description: "Nombre de produits à fabriquer dans les 24 prochain mois",
        inputType: "select",
        select: [
          "Moins de 10",
          "Moins de 100",
          "Moins de 500",
          "Moins de 1000",
          "Moins de 5000",
          "Moins de 10000",
          "Moins de 50000",
          "Moins de 100000",
          "Plus de 100000",
        ],
        value: "",
        isBranch: false,
      },
      {
        name: "fabrication36",
        question: "Nombre de produits à fabriquer",
        description: "Nombre de produits à fabriquer dans les 36 prochain mois",
        inputType: "select",
        select: [
          "Moins de 10",
          "Moins de 100",
          "Moins de 500",
          "Moins de 1000",
          "Moins de 5000",
          "Moins de 10000",
          "Moins de 50000",
          "Moins de 100000",
          "Plus de 100000",
        ],
        value: "",
        isBranch: false,
      },
      {
        name: "budget",
        question: "Budget prévu",
        description:
          "Quel budget a été prévu pour la réalisation de votre produit ?",
        inputType: "select",
        select: [
          "Moins de 50000",
          "Moins de 100000",
          "Moins de 150000",
          "Moins de 200000",
          "Moins de 250000",
          "Moins de 300000",
          "Plus de 300000",
        ],
        value: "",
        isBranch: false,
      },
    ],
  },
  {
    name: "marches",
    question: "Marchés",
    description: "Quels marchés visez-vous avec ce projet ?",
    inputType: "multiChoice",
    multiChoice: [
      "Agriculture",
      "Banque",
      "Eclairage connecté",
      "Logistique",
      "Stationnement connecté",
      "Séniors",
      "Agroalimentaire",
      "Batiment connecté",
      "Energie/Eau",
      "Maison connectée",
      "Santé",
      "Transport",
      "Assurance",
      "Construction / BTP",
      "Industriel",
      "Marché publique",
      "Sécurité",
      "Autre",
    ],
    value: [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
    isBranch: false,
  },
  {
    name: "geographie",
    question: "Zone Géographique",
    description:
      "Dans quelles zones géographiques votre produit seratil utilisé ?",
    inputType: "multiChoice",
    multiChoice: [
      "Europe",
      "Amérique du nord",
      "Amérique du sud",
      "Asie",
      "Australasie",
      "Japon",
    ],
    value: [false, false, false, false, false, false],
    isBranch: false,
  },
  {
    branch: "end",
    isDisplayed: true,
    title: "Dernière ligne droite",
    components: [
      {
        name: "ecoConception",
        question: "Vision écologique",
        description:
          "Dans le cadre de votre projet, avez-vous inclus des éléments tels que :",
        inputType: "multiChoice",
        multiChoice: [
          "Eco-conception",
          "Schéma d'économie circulaire",
          "Intégration de matière plastique recyclée",
          "Autre",
        ],
        value: [false, false, false, false],
        isBranch: false,
      },
      {
        name: "sourceContact",
        question: "Comment nous connaissez-vous",
        description: "Comment nous avez-vous connu ?",
        inputType: "multiChoice",
        multiChoice: [
          "par une recherche sur internet",
          "par Linkedin",
          "par un autre réseau social (Twitter, facebook, ...)",
          "par mon réseau",
          "par un média (presse, TV, ...)",
          "sur un évènement",
          "autre",
        ],
        value: [false, false, false, false, false, false, false],
        isBranch: false,
      },
      {
        name: "email",
        question: "E-Mail",
        description: "Quel est votre e-mail",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "tel",
        question: "Téléphone",
        description: "Quel est votre téléphone",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "adresse",
        question: "Adresse",
        description: "Quel est votre adresse (150 rue du generale de gaule)",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "ville",
        question: "Ville",
        description: "Quel est votre ville (Paris)",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "codePostal",
        question: "Code Postal",
        description: "Quel est votre code postal (75015)",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "pays",
        question: "Pays",
        description: "Quel est votre pays (France)",
        inputType: "textField",
        isBranch: false,
        value: "",
      },
      {
        name: "emailMarketing",
        question: "Marketing ?",
        description:
          "J'accepte de recevoir des e-mails marketing de la part d'ALTYOR (newsletters, actualités, évènements, etc.). Promis, on ne vous embêtera pas plus d'une fois par mois.",
        inputType: "radio",
        radio: ["oui", "non"],
        value: "",
        isBranch: false,
      },
      {
        name: "acceptation",
        question: "RGPD",
        description:
          "En soumettant ce formulaire, j'accepte que les informations saisies soient stockées et exploitées dans le cadre de la relation commerciale qui peut en découler. Vous pouvez demander à supprimer vos données à tout moment.",
        inputType: "radio",
        radio: ["oui", "non"],
        value: "",
        isBranch: false,
      },
    ],
  },
];

export default dataStructure;
